---
- hosts: 127.0.0.1
  connection: local
  roles:
    - role: 'roles/generate-ssh-credential'

- hosts: demo
  user: ansadmin
  become: yes
  connection: ssh
  gather_facts: yes

  roles:
    - role: 'roles/assign-user-group'
  
- hosts: 127.0.0.1
  connection: local
  roles:
      - role: 'roles/send-user-email'
