- name: create a directory for ssh user {{user_name}}
  file:
    path: /root/.ssh/{{group}}/{{user_name}}
    state: directory

- name: create a ssh key for user {{user_name}}
  openssh_keypair:
    path:  "/root/.ssh/{{group}}/{{user_name}}/id_{{user_name}}"
    type: rsa
    size: 4096
    state: present
    force: no


- name: encrypt private key for user {{user_name}}
  command: openssl rsa -in /root/.ssh/{{group}}/{{user_name}}/id_{{user_name}} -out /root/.ssh/{{group}}/{{user_name}}/id_{{user_name}}.pem
  register: encrypt_private

- debug:
    msg: "{{encrypt_private}}"


- name: Convert private key for user {{user_name}} to PKCS8 format with passphrase
  community.crypto.openssl_privatekey_convert:
    src_path: /root/.ssh/{{group}}/{{user_name}}/id_{{user_name}}.pem
    dest_path: /root/.ssh/{{group}}/{{user_name}}/id_{{user_name}}.key
    dest_passphrase: '{{passphrase}}'
    format: pkcs8 
