---
# tasks file for roles/assign-user-group
- name: Install the correct web server for RHEL
  import_tasks: redhat/redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the correct web server for Debian
  import_tasks: debian/debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
